#!/usr/bin/env python3
"""
txn.py — XAIE Transaction Buffer parser/disassembler

The transaction buffer is the runtime control sequence that the host
sends to the NPU to orchestrate DMA transfers and kernel execution.
It is distinct from the CDO in the xclbin (which initialises the AIE
hardware) — the transaction buffer is generated at runtime by the
application (e.g. FastFlowLM's npu_sequence class) and assembled into
an ELF by aiebu before dispatch.

Opcode reference: FastFlowLM include/npu_utils/instr_utils/npu_cmd*.hpp
                  mlir-aie/lib/Dialect/AIEX/IR/AIEXDialect.cpp
                  mlir-aie/lib/Targets/AIETargetNPU.cpp
"""

from __future__ import annotations
import struct
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional


# ── Opcodes ──────────────────────────────────────────────────────────────────

class Op(IntEnum):
    WRITE           = 0x00   # write single 32-bit register
    BLOCKWRITE      = 0x01   # write N consecutive words (for tile PM or DM)
    BLOCKSET        = 0x02   # set N words to a constant value
    MASKWRITE       = 0x03   # read-modify-write with mask  (push queue / issue token)
    MASKPOLL        = 0x04   # poll register until (val & mask) == expected
    NOOP            = 0x05
    PREEMPT         = 0x06
    MASKPOLL_BUSY   = 0x07
    LOADPDI         = 0x08
    LOAD_PM_START   = 0x09
    CREATE_SCRATCH  = 0x0A
    UPDATE_STATE    = 0x0B
    UPDATE_REG      = 0x0C
    UPDATE_SCRATCH  = 0x0D
    SHIMDMA_BD      = 0x0E   # configure a shim DMA buffer descriptor
    SHIMDMA_BUF_BD  = 0x0F   # configure a shim DMA BO buffer descriptor
    # Custom / high-level ops (generated by mlir-aie AIEX passes)
    TCT             = 0x80   # trigger completion token
    DDR_PATCH       = 0x81   # patch a BD address field with a DDR BO address
    READ_REGS       = 0x82
    RECORD_TIMER    = 0x83
    MERGE_SYNC      = 0x84


OP_NAMES = {int(o): o.name for o in Op}
# Empirically identified opcodes not in the XAIE2 standard set:
OP_NAMES[0x30] = "DMA_BD_FENCE"   # 1-word DMA transaction fence; precedes each BD setup group


# ── Address helpers ───────────────────────────────────────────────────────────

BD_COL_SHIFT = 25
BD_ROW_SHIFT = 20
BD_COL_MASK  = 0x7F
BD_ROW_MASK  = 0x1F

def decode_addr(word: int) -> tuple[int, int, int]:
    """Return (col, row, reg_offset) from an AIE tile address word."""
    col = (word >> BD_COL_SHIFT) & BD_COL_MASK
    row = (word >> BD_ROW_SHIFT) & BD_ROW_MASK
    reg = word & 0xFFFFF
    return col, row, reg

QUEUE_REGS = {
    # (S2MM=0/MM2S=1, channel) → queue register name
    (0, 0): "DMA_S2MM_0_TASK_QUEUE",
    (0, 1): "DMA_S2MM_1_TASK_QUEUE",
    (1, 0): "DMA_MM2S_0_TASK_QUEUE",
    (1, 1): "DMA_MM2S_1_TASK_QUEUE",
}

SHIM_BD_BASE = 0x1D000      # shim DMA BD register base offset


# ── Decoded instruction dataclasses ─────────────────────────────────────────

@dataclass
class Instr:
    offset: int       # byte offset in stream
    opcode: int
    words: list[int]  # raw words

    @property
    def op_name(self) -> str:
        return OP_NAMES.get(self.opcode, f"UNK_0x{self.opcode:02x}")

    def describe(self) -> str:
        return f"[0x{self.offset:06x}] {self.op_name}"


@dataclass
class WriteInstr(Instr):
    col: int
    row: int
    reg: int
    value: int
    is_push_queue: bool = False
    direction: str = ""     # "S2MM" or "MM2S"
    channel: int = 0
    bd_id: int = 0
    repeat: int = 0
    issue_token: bool = False

    def describe(self) -> str:
        if self.is_push_queue:
            dir_sym = "→" if self.direction == "MM2S" else "←"
            tok = " +TOKEN" if self.issue_token else ""
            return (f"[0x{self.offset:06x}] PUSH_QUEUE  tile({self.col},{self.row})  "
                    f"{self.direction}_ch{self.channel}  bd={self.bd_id}  "
                    f"repeat={self.repeat}{tok}")
        return (f"[0x{self.offset:06x}] WRITE       tile({self.col},{self.row})  "
                f"reg=0x{self.reg:05x}  val=0x{self.value:08x}")


@dataclass
class BlockWriteInstr(Instr):
    col: int
    row: int
    reg: int
    count: int        # number of 32-bit words
    payload: list[int] = field(repr=False, default_factory=list)

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] BLOCKWRITE  tile({self.col},{self.row})  "
                f"reg=0x{self.reg:05x}  words={self.count}")


@dataclass
class MaskWriteInstr(Instr):
    col: int
    row: int
    reg: int
    value: int
    mask: int
    direction: str
    channel: int
    pkt_id: int

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] ISSUE_TOKEN tile({self.col},{self.row})  "
                f"{self.direction}_ch{self.channel}  pkt_id=0x{self.pkt_id:x}  "
                f"mask=0x{self.mask:08x}")


@dataclass
class DdrPatchInstr(Instr):
    col: int
    row: int
    bd_id: int
    arg_idx: int
    arg_offset: int

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] DDR_PATCH   tile({self.col},{self.row})  "
                f"bd={self.bd_id}  arg[{self.arg_idx}]+0x{self.arg_offset:x}")


@dataclass
class ShimDmaBdInstr(Instr):
    col: int
    row: int
    bd_id: int
    buf_len: int        # in 32-bit words
    buf_offset: int
    direction: str
    # addressing / tiling
    dim0_size: int = 0
    dim0_stride: int = 0
    dim1_size: int = 0
    dim1_stride: int = 0
    dim2_size: int = 0
    dim2_stride: int = 0
    # chaining
    next_bd: int = 0
    use_next_bd: bool = False
    valid: bool = True
    # packet switching
    pkt_enable: bool = False
    pkt_id: int = 0
    pkt_type: int = 0
    repeat: int = 0
    issue_token: bool = False

    def describe(self) -> str:
        dims = f"  [{self.buf_len}w off={self.buf_offset:x}]"
        tiling = ""
        if self.dim0_size:
            tiling = f"  d0={self.dim0_size}×{self.dim0_stride}"
        if self.dim1_size:
            tiling += f"  d1={self.dim1_size}×{self.dim1_stride}"
        if self.dim2_size:
            tiling += f"  d2={self.dim2_size}×{self.dim2_stride}"
        chain = f"  →bd{self.next_bd}" if self.use_next_bd else ""
        return (f"[0x{self.offset:06x}] SHIMDMA_BD  tile({self.col},{self.row})  "
                f"bd={self.bd_id}{dims}{tiling}{chain}")


# ── Parser ───────────────────────────────────────────────────────────────────

class TxnParser:
    """Parse a raw XAIE transaction buffer (list of uint32 words or bytes)."""

    def __init__(self, words: list[int]):
        self.words = words
        self.pos = 0
        self.instrs: list[Instr] = []

    # --- helpers ---

    def _peek(self, n: int = 1) -> list[int]:
        return self.words[self.pos: self.pos + n]

    def _read(self, n: int) -> list[int]:
        chunk = self.words[self.pos: self.pos + n]
        self.pos += n
        return chunk

    # --- main loop ---

    def parse(self) -> list[Instr]:
        self.instrs = []
        while self.pos < len(self.words):
            byte_off = self.pos * 4
            opcode = self.words[self.pos] & 0xFF

            if opcode == Op.WRITE:
                self._parse_write(byte_off)
            elif opcode == Op.BLOCKWRITE:
                self._parse_blockwrite(byte_off)
            elif opcode == Op.MASKWRITE:
                self._parse_maskwrite(byte_off)
            elif opcode == Op.DDR_PATCH:
                self._parse_ddr_patch(byte_off)
            elif opcode == Op.SHIMDMA_BD:
                self._parse_shimdma_bd(byte_off)
            elif opcode == Op.TCT:
                # TCT (trigger completion token) — 3 words: op, col/row, padding
                w = self._read(3)
                self.instrs.append(Instr(byte_off, opcode, w))
            elif opcode == Op.NOOP:
                w = self._read(1)
                self.instrs.append(Instr(byte_off, opcode, w))
            else:
                # Unknown opcodes — use bits[31:24] of op word as instruction
                # size (in words) when available; fall back to skip-1.
                maybe_size = (self.words[self.pos] >> 24) & 0xFF
                if 1 < maybe_size <= 64:
                    n = maybe_size
                elif self.pos + 1 < len(self.words):
                    raw_size = (self.words[self.pos + 1] >> 2) & 0x3FFFFF
                    n = raw_size if 1 < raw_size <= 64 else 1
                else:
                    n = 1
                n = min(n, len(self.words) - self.pos)
                w = self._read(n)
                self.instrs.append(Instr(byte_off, opcode, w))
        return self.instrs

    def _parse_write(self, byte_off: int):
        # 6 words: [opcode][unused][addr_word][unused][value][op_size<<2]
        # Guard: if < 6 words remain, read what we can and emit unknown
        if self.pos + 6 > len(self.words):
            w = self._read(len(self.words) - self.pos)
            self.instrs.append(Instr(byte_off, Op.WRITE, w))
            return
        w = self._read(6)
        col, row, reg = decode_addr(w[2])
        value = w[4]
        is_queue = (reg & 0x1FE00) == 0x1D200
        instr = WriteInstr(
            offset=byte_off, opcode=Op.WRITE, words=w,
            col=col, row=row, reg=reg, value=value,
            is_push_queue=is_queue,
        )
        if is_queue:
            instr.direction = "MM2S" if (reg & 0x10) else "S2MM"
            instr.channel = (reg >> 3) & 0x1
            instr.bd_id = value & 0xF
            instr.repeat = (value >> 16) & 0xFF
            instr.issue_token = bool(value >> 31)
        self.instrs.append(instr)

    def _parse_blockwrite(self, byte_off: int):
        # word[0]=opcode, word[1]=addr, word[2]=count, word[3..N]=data
        # Some formats encode count in header[0] bits[31:16] instead of header[2]
        header = self._read(3)
        opcode = header[0] & 0xFF
        col, row, reg = decode_addr(header[1])
        # Use header[2] as count; sanity-check against remaining words
        count = header[2]
        if count > len(self.words) - self.pos:
            count = len(self.words) - self.pos
        payload = self._read(count)
        all_words = header + payload
        self.instrs.append(BlockWriteInstr(
            offset=byte_off, opcode=opcode, words=all_words,
            col=col, row=row, reg=reg, count=count, payload=payload,
        ))

    def _parse_maskwrite(self, byte_off: int):
        # 7 words: [op][unused][addr][unused][value][mask][op_size]
        w = self._read(7)
        col, row, reg = decode_addr(w[2])
        value = w[4]
        mask = w[5]
        direction = "MM2S" if (reg & 0x10) else "S2MM"
        channel = (reg >> 3) & 0x1
        pkt_id = (value >> 8) & 0xFFFFFF
        self.instrs.append(MaskWriteInstr(
            offset=byte_off, opcode=Op.MASKWRITE, words=w,
            col=col, row=row, reg=reg, value=value, mask=mask,
            direction=direction, channel=channel, pkt_id=pkt_id,
        ))

    def _parse_ddr_patch(self, byte_off: int):
        # 12 words: [op][size<<2][0][0][0][0][bd_reg][0][arg_idx][0][arg_off][0]
        w = self._read(12)
        bd_reg = w[6]
        col = (bd_reg >> BD_COL_SHIFT) & BD_COL_MASK
        row = (bd_reg >> BD_ROW_SHIFT) & BD_ROW_MASK
        bd_id = ((bd_reg - 0x04) >> 5) & 0x1F
        arg_idx = w[8]
        arg_offset = w[10]
        self.instrs.append(DdrPatchInstr(
            offset=byte_off, opcode=Op.DDR_PATCH, words=w,
            col=col, row=row, bd_id=bd_id,
            arg_idx=arg_idx, arg_offset=arg_offset,
        ))

    def _parse_shimdma_bd(self, byte_off: int):
        # 12 words per BD configure command — from npu_cmd_write_dma.hpp
        w = self._read(12)
        # word[0] = (is_bd<<12)|(col<<25)|(row<<20)|(bd_id<<5) | Op
        op_word = w[0]
        col = (op_word >> BD_COL_SHIFT) & BD_COL_MASK
        row = (op_word >> BD_ROW_SHIFT) & BD_ROW_MASK
        bd_id = (op_word >> 5) & 0xF
        # word[1] = buffer_length
        buf_len = w[1]
        # word[2] = buffer_offset
        buf_offset = w[2]
        # word[3] = packet/enable flags
        pkt_enable = bool((w[3] >> 30) & 1)
        pkt_id = (w[3] >> 19) & 0x1F
        pkt_type = (w[3] >> 16) & 0x7
        # word[4] = dim0 (size<<20 | stride)
        dim0_stride = w[4] & 0xFFFFF
        dim0_size = (w[4] >> 20) & 0x3FF
        # word[5] = dim1
        dim1_stride = w[5] & 0xFFFFF
        dim1_size = (w[5] >> 20) & 0x3FF
        # word[6] = iter/dim2
        iter_stride = w[6] & 0xFFFFF
        iter_size = (w[6] >> 20) & 0x3FF
        # word[7] = dim2
        dim2_stride = w[7] & 0xFFFFF
        dim2_size = (w[7] >> 20) & 0x3FF
        # word[8] = lock acquire/release
        # word[9] = next bd / valid
        next_bd = (w[9] >> 27) & 0xF
        use_next = bool((w[9] >> 26) & 1)
        valid = bool((w[9] >> 25) & 1)
        # word[10] = repeat/token
        repeat = (w[10] >> 16) & 0xFF if len(w) > 10 else 0
        issue_token = bool(w[10] >> 31) if len(w) > 10 else False

        self.instrs.append(ShimDmaBdInstr(
            offset=byte_off, opcode=Op.SHIMDMA_BD, words=w,
            col=col, row=row, bd_id=bd_id,
            buf_len=buf_len, buf_offset=buf_offset,
            dim0_size=dim0_size, dim0_stride=dim0_stride,
            dim1_size=dim1_size, dim1_stride=dim1_stride,
            dim2_size=dim2_size, dim2_stride=dim2_stride,
            next_bd=next_bd, use_next_bd=use_next, valid=valid,
            pkt_enable=pkt_enable, pkt_id=pkt_id, pkt_type=pkt_type,
            repeat=repeat, issue_token=issue_token,
        ))


def from_bytes(data: bytes) -> list[Instr]:
    """Parse a raw transaction buffer from bytes."""
    words = list(struct.unpack_from(f"<{len(data)//4}I", data))
    return TxnParser(words).parse()


def from_words(words: list[int]) -> list[Instr]:
    return TxnParser(words).parse()


def describe_all(instrs: list[Instr]) -> str:
    return "\n".join(i.describe() for i in instrs)


# ── DMA topology extractor ────────────────────────────────────────────────────

@dataclass
class DmaTransfer:
    direction: str     # "H2D" (host-to-device) or "D2H"
    arg_idx: int       # which kernel buffer arg
    arg_offset: int
    col: int
    bd_id: int
    buf_len: int       # words
    strides: list[tuple[int, int]]  # [(size,stride), ...]

    def describe(self) -> str:
        dir_arrow = "→NPU" if self.direction == "H2D" else "←NPU"
        dims = "  ".join(f"[{s}×{st}]" for s, st in self.strides if s)
        return (f"arg[{self.arg_idx}]+{self.arg_offset:#x}  {dir_arrow}  "
                f"col={self.col} bd={self.bd_id}  len={self.buf_len*4}B  {dims}")


def extract_dma_topology(instrs: list[Instr]) -> list[DmaTransfer]:
    """
    Correlate DDR_PATCH instructions with SHIMDMA_BD descriptors to produce
    a human-readable table of host↔NPU DMA transfers.
    """
    # Index BDs by (col, row, bd_id)
    bds: dict[tuple, ShimDmaBdInstr] = {}
    for i in instrs:
        if isinstance(i, ShimDmaBdInstr):
            bds[(i.col, i.row, i.bd_id)] = i

    transfers: list[DmaTransfer] = []
    for i in instrs:
        if not isinstance(i, DdrPatchInstr):
            continue
        bd = bds.get((i.col, i.row, i.bd_id))
        if bd is None:
            continue
        # direction: shim row=0 S2MM means host→device for data buffers
        direction = "H2D"   # refine later from push-queue context
        strides = [
            (bd.dim0_size, bd.dim0_stride),
            (bd.dim1_size, bd.dim1_stride),
            (bd.dim2_size, bd.dim2_stride),
        ]
        transfers.append(DmaTransfer(
            direction=direction,
            arg_idx=i.arg_idx,
            arg_offset=i.arg_offset,
            col=i.col,
            bd_id=i.bd_id,
            buf_len=bd.buf_len,
            strides=strides,
        ))
    return transfers


# ── DMA BD group extractor ────────────────────────────────────────────────────
#
# In the aiebu DPU ctrltext, each shim DMA BD is programmed by a "BD group":
#   DMA_BD_FENCE (1 word, opcode 0x30) followed by exactly 6 WRITEs (36 words)
#
# The 6 WRITEs are:
#   [0] DDR addr_low placeholder  — RELA type-5 patches w[0] with actual DDR addr
#       reg=0x0 (decoded from w[2]=0), w[4]=BD_ctrl_word
#   [1] DMA size/config           — reg=0x81 (or col-encoded), val=0
#   [2] BD.word1 (addr_high)      — reg=BD_base+4|col_bits, val=addr_hi (DDR bits[39:32])
#   [3] Queue kickoff (indirect)  — reg=0x3, val=queue_register_address
#   [4] Status clear              — reg=0x1c, val=0
#   [5] DMA enable/control        — reg=0x18, val=0
#
# The BD and column are identified from WRITE[2]'s register address.
# RELA r_offset points to the START of WRITE[0] (i.e., its w[0] = DDR addr_low slot).

# Shim DMA channel queue registers (tile-local offsets, col bits added at runtime)
_SHIM_QUEUE_REGS: dict[int, tuple[str, int]] = {
    0x1d200: ("S2MM", 0), 0x1d204: ("S2MM", 0),
    0x1d208: ("S2MM", 1), 0x1d20c: ("S2MM", 1),
    0x1d210: ("MM2S", 0), 0x1d214: ("MM2S", 0),
    0x1d218: ("MM2S", 1), 0x1d21c: ("MM2S", 1),
}


@dataclass
class DmaBdGroup:
    """One DMA BD programming group decoded from a DMA_BD_FENCE + 6 WRITEs sequence."""
    fence_instr_idx: int    # index of the DMA_BD_FENCE instruction
    addr_write_idx: int     # index of WRITE[0] (the one whose w[0] is RELA-patched)
    ddr_addr_lo_placeholder: int  # w[0] before RELA patching (e.g. 0x00010000)
    bd_ctrl: int            # BD control word from WRITE[0].w[4]
    col: int                # shim column (from WRITE[2]'s register address bits[31:25])
    bd_id: int              # BD index within the column's shim DMA (0..15)
    addr_hi: int            # DDR addr bits[39:32] (from WRITE[2].value)
    direction: str          # "MM2S" or "S2MM" or "?"
    channel: int            # DMA channel index (0 or 1), -1 if unknown

    def describe(self) -> str:
        dir_arrow = "→NPU" if self.direction == "MM2S" else "←NPU"
        return (f"DMA_BD_GROUP  col={self.col}  bd={self.bd_id}  "
                f"{self.direction}_ch{self.channel}  {dir_arrow}  "
                f"ddr_hi={self.addr_hi}  ctrl=0x{self.bd_ctrl:08x}")


def find_dma_bd_groups(instrs: list[Instr]) -> list[DmaBdGroup]:
    """Scan the instruction stream for DMA_BD_FENCE + 6 WRITEs patterns.

    Each such group programs one shim DMA BD with a DDR buffer address.
    The first WRITE's w[0] is the RELA relocation target (DDR addr_low placeholder).
    Returns one DmaBdGroup per fence found.
    """
    groups: list[DmaBdGroup] = []
    for fi, instr in enumerate(instrs):
        if instr.opcode != 0x30:
            continue
        # Need at least 6 more instructions
        if fi + 6 >= len(instrs):
            continue
        # WRITE[0]: DDR addr_lo write — reg must be 0, w[0] is RELA target
        addr_w = instrs[fi + 1]
        if not isinstance(addr_w, WriteInstr) or addr_w.reg != 0:
            continue
        placeholder = addr_w.words[0] if addr_w.words else 0
        bd_ctrl = addr_w.words[4] if len(addr_w.words) > 4 else 0

        # WRITE[2]: BD.word1 → col and bd_id
        bd_word1_w = instrs[fi + 3]
        col, bd_id, addr_hi = -1, -1, -1
        if isinstance(bd_word1_w, WriteInstr):
            r = bd_word1_w.reg
            if 0x1d004 <= r <= 0x1d1fc and (r - 0x1d004) % 0x20 == 0:
                col = bd_word1_w.col
                bd_id = (r - 0x1d004) // 0x20
                addr_hi = bd_word1_w.value

        # WRITE[3]: queue kickoff → direction and channel (value encodes queue reg)
        queue_w = instrs[fi + 4]
        direction, channel = "?", -1
        if isinstance(queue_w, WriteInstr):
            qv = queue_w.value & 0x1FFFFF  # strip column bits
            if qv in _SHIM_QUEUE_REGS:
                direction, channel = _SHIM_QUEUE_REGS[qv]

        groups.append(DmaBdGroup(
            fence_instr_idx=fi,
            addr_write_idx=fi + 1,
            ddr_addr_lo_placeholder=placeholder,
            bd_ctrl=bd_ctrl,
            col=col,
            bd_id=bd_id,
            addr_hi=addr_hi,
            direction=direction,
            channel=channel,
        ))
    return groups

